# Generated by Django 5.2 on 2026-09-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='work_model',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('in_person', 'In-person'), ('hybrid', 'Hybrid')], max_length=20, null=True),
        ),
    ]
